### PR TITLE
Calculate headers once

### PR DESCRIPTION
**Pull request by britishtea**
Instead of calculating security headers for every request, this patch calculates them once when the middleware is mounted. `Hash#merge!` is used to add the headers to the response.

The main benefit of this approach is that it is roughly 1.25 to 1.5 times faster. I've used the following benchmarks (which requires the `benchmark-ips` gem) to measure the impact.

``` ruby
require "benchmark/ips"
require_relative "lib/rack/secure_headers"

class App
  def call(env)
    return [200, {}, [""]]
  end
end

Benchmark.ips do |x|
  original = Rack::SecureHeadersOriginal.new(App.new)
  x.report "original" do
    original.call({})
  end

  refactored = Rack::SecureHeaders.new(App.new)
  x.report "refactored" do
    refactored.call({})
  end

  x.compare!
end
```

It yielded the following result on my machine:

```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
$ ruby bench.rb
Calculating -------------------------------------
            original    24.987k i/100ms
          refactored    48.216k i/100ms
-------------------------------------------------
            original    302.402k (± 4.1%) i/s -      1.524M
          refactored    746.354k (± 6.0%) i/s -      3.761M

Comparison:
          refactored:   746353.5 i/s
            original:   302401.7 i/s - 2.47x slower
```

### CODE REVIEW

**Comment by frodsan** [comment]
Looks good! Thanks!

**Comment by frodsan** [comment]
0.0.2 released: https://rubygems.org/gems/rack-secure_headers/versions/0.0.2

Thanks again!

**Comment by frodsan** [comment]
@britishtea Hi! I'm working in something like Cuba. I would like to know if you are interested in review it? Thanks in advance :-)

**Comment by britishtea** [comment]
@frodsan Sure!

**Comment by frodsan** [comment]
@britishtea I send you an invite. I created a channel in Slack if you are interested in give feedback, etc. If you don't use Slack, you can ping me at frodsan@protonmail.ch. Thanks!

**Pull request merged**
